package ui;


import utils.Launcher;
import java.awt.Cursor;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on Jun 21, 2010, 1:07:44 PM
 */

/**
 *
 * @author Kanishka Dilshan
 */
public class About extends javax.swing.JFrame {

    /** Creates new form About */
    public About() {
        initComponents();
        jLabel4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel6.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bopath.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 36)); // NOI18N
        jLabel2.setText("ධම්ම පාසාදිකය");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/88x31.png"))); // NOI18N
        jButton2.setText("View The Licence");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectLogoMini.png"))); // NOI18N

        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tipitaka_Sinhala1", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(";1smsglh Ndjs;d lrk  fnd fyda mskaj;2kag ;sfnk .eg,qjla jk huz lsis iQ;1foaYkdjla ;1smsglh ;2, wka;rA.; jkafka fl2uk ia:dkfhao hkak ksrdlrKh lr.ekSfuz wgsfhka fuu uDÈldx.h ksrAudKh lr we;' Bg wu;rj Tng huz lsis OrAu lreKla W;2uz ;1smsglh ;2, l2uk ia:dkhkays wka;rA.; jkafkao hkak Tng fuu fijquz jevigyk u.ska fid hd.; yelsh' WodyrKhla f,i Ùi;smgzGdkhÙ hkqfjka fijSula lsrSfuka ;1smsglh ;2, Ùi;smgzGdkhÙ hk jok fhoS we;s iEu wjia:djlau fijquz m1;sM, f,i ,efnkq we;'\n\nfuu mrs.Kl jevigyk oshqKq lsrSug Tnf.a woyia b;d jeo.;a fjz' fuys isÈjsh hq;2 fjkialuz hkdosh wmfj; ,enSug ie,eiajSfuka Tng fuz iËyd odhl jsh yelsh' wm fuysoS fhdodf.k we;af;a fu;a;dfkgz fjnz wvjsh jsiska ksfl2;alr we;s ;1smsgl fmd;a jykafiah' tu fiajdj lrf.k hk mskaj;a iajduSka jykafia,dgo ta yd iuznkao ish,q mskaj;2kago fuz f.#;u nqÈrcdKka jykafiaf.a iiqk ;2,oSu W;2uz p;2rdrAh i;H wjfndaO lsrSug ,efnzjd\nf;rejka irKhs'");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mettanet.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DhammaMedicine.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setText("V 1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        URL url= getClass().getResource("/ico2.png");
        ImageIcon imageIcon = new ImageIcon(url);
        Image image = imageIcon.getImage();
        License lc=new License();
        lc.setVisible(true);
        lc.setIconImage(image);
        lc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        //new BLauncher("http://www.metta.lk/");
        new Launcher().launch("http://www.metta.lk/");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //new BLauncher("http://dhammamedicine.net");
        new Launcher().launch("http://dhammamedicine.net");
    }//GEN-LAST:event_jLabel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

//    class BLauncher extends Thread{
//        String url;
//        public BLauncher(String url){
//            this.url=url;
//            this.start();
//        }
//
//        @Override
//        public void run(){
//            try{
//                URI tripitaka=new URI(this.url);
//                //java.awt.Desktop.getDesktop().browse(tripitaka);
//                win7launch(tripitaka.getPath());    //only for windows 7
//            }catch(URISyntaxException e){
//                JOptionPane.showMessageDialog(null, e.getMessage() ,"Error!",JOptionPane.ERROR_MESSAGE);
//            }
//        }
//
//        private void win7launch(String path) {
//            try {
//                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + path);
//            } catch (IOException ex) {
//                System.out.println(ex.getMessage());
//            }
//        }
//    }

}
