package ui;


import utils.Launcher;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import update.UpdateCheckProcess;
import update.UpdateDetails;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CheckForUpdates.java
 *
 * Created on May 23, 2011, 8:44:55 AM
 */

/**
 *
 * @author Kanishka
 */
public class CheckForUpdates extends javax.swing.JDialog {

    /** Creates new form CheckForUpdates */
    UpdateCheckProcess updateCheck;
    public CheckForUpdates(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanel_update.setVisible(false);
        jLabel_Err.setVisible(false);

        UpdateDetails updtDtls=new UpdateDetails();
        updtDtls.setjLabel_updateStatus(jLabel_updateStatus);
        updtDtls.setjLabel_updateURL(jLabel_updateURL);
        updtDtls.setjLabel_updatetype(jLabel_updatetype);
        updtDtls.setjLabel_version(jLabel_version);
        updtDtls.setjPanel_update(jPanel_update);
        updtDtls.setjTextArea_updateDescription(jTextArea_updateDescription);

        //update thread
        updateCheck=new UpdateCheckProcess(jLabel_Err, jLabel_loading,updtDtls);
        updateCheck.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_loading = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Err = new javax.swing.JLabel();
        jPanel_update = new javax.swing.JPanel();
        jLabel_updateStatus = new javax.swing.JLabel();
        jLabel_version = new javax.swing.JLabel();
        jLabel_updatetype = new javax.swing.JLabel();
        jLabel_updateStatus3 = new javax.swing.JLabel();
        jLabel_updateURL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_updateDescription = new javax.swing.JTextArea();
        jButton_dwnld = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Update");
        setAlwaysOnTop(true);
        setResizable(false);
        setUndecorated(true);

        jLabel_loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/70.gif"))); // NOI18N
        jLabel_loading.setText("Checking for newer versions");
        jLabel_loading.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel_loading.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Software Update");

        jLabel_Err.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Err.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bug.png"))); // NOI18N
        jLabel_Err.setText("Connection Error!");

        jPanel_update.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_updateStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_updateStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_updateStatus.setText("Update Status");

        jLabel_version.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_version.setText("Version : ");

        jLabel_updatetype.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_updatetype.setText("Update Type :");

        jLabel_updateStatus3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_updateStatus3.setText("Description");

        jLabel_updateURL.setForeground(new java.awt.Color(0, 51, 255));
        jLabel_updateURL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_updateURL.setText("URL :");

        jTextArea_updateDescription.setColumns(20);
        jTextArea_updateDescription.setEditable(false);
        jTextArea_updateDescription.setLineWrap(true);
        jTextArea_updateDescription.setRows(5);
        jScrollPane1.setViewportView(jTextArea_updateDescription);

        jButton_dwnld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/down.png"))); // NOI18N
        jButton_dwnld.setText("Download!");
        jButton_dwnld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dwnldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_updateLayout = new javax.swing.GroupLayout(jPanel_update);
        jPanel_update.setLayout(jPanel_updateLayout);
        jPanel_updateLayout.setHorizontalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_updateStatus3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_updatetype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_version, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(jLabel_updateStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addComponent(jLabel_updateURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(664, 664, 664))
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addComponent(jButton_dwnld)
                        .addContainerGap(391, Short.MAX_VALUE))))
        );
        jPanel_updateLayout.setVerticalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_updateStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_version)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_updatetype)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_updateStatus3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_updateURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_dwnld)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_loading, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_update, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Err, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_loading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel_Err))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateCheck.stop();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_dwnldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dwnldActionPerformed
        // TODO add your handling code here:
        //BLauncher blnch=new BLauncher(jLabel_updateURL.getText());
        new Launcher().launch(jLabel_updateURL.getText());
        this.dispose();
    }//GEN-LAST:event_jButton_dwnldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckForUpdates dialog = new CheckForUpdates(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_dwnld;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Err;
    private javax.swing.JLabel jLabel_loading;
    private javax.swing.JLabel jLabel_updateStatus;
    private javax.swing.JLabel jLabel_updateStatus3;
    private javax.swing.JLabel jLabel_updateURL;
    private javax.swing.JLabel jLabel_updatetype;
    private javax.swing.JLabel jLabel_version;
    private javax.swing.JPanel jPanel_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_updateDescription;
    // End of variables declaration//GEN-END:variables

//        class BLauncher extends Thread{
//        String url;
//        public BLauncher(String url){
//            this.url=url;
//            this.start();
//        }
//
//        @Override
//        public void run(){
//            try{
//                URI tripitaka=new URI(this.url);
//                java.awt.Desktop.getDesktop().browse(tripitaka);
//            }catch(URISyntaxException e){
//                JOptionPane.showMessageDialog(null, e.getMessage() ,"Error!",JOptionPane.ERROR_MESSAGE);
//            }catch(IOException e){
//                JOptionPane.showMessageDialog(null, e.getMessage() ,"Error!",JOptionPane.ERROR_MESSAGE);
//            }catch(Exception e){
//                JOptionPane.showMessageDialog(null, "Your JVM doesn't support this feature.\nPlease update your JVM.\n"+e.getMessage() ,"Error!",JOptionPane.ERROR_MESSAGE);
//            }
//        }
//    }
}
