package ui;


import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UnicodePopup.java
 *
 * Created on May 13, 2011, 1:13:46 AM
 */

/**
 *
 * @author Kanishka
 */
public class UnicodePopup extends javax.swing.JFrame {
    JTextField jtf=null;
    JButton srchBtn=null;
    JButton launchBtn=null;

    /** Creates new form UnicodePopup */
    public UnicodePopup() {
        this.setUndecorated(true);
        initComponents();
        this.setVisible(true);
        jTextField1.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

        jTextField1.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complete.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        convertToTripitakaSin();
        this.launchBtn.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        this.jtf.setText("");
        this.launchBtn.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == evt.VK_ENTER && jTextField1.getText().length()!=0) {
            jButton3.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        convertToTripitakaSin();
        this.dispose();
        this.srchBtn.doClick();
        this.launchBtn.setEnabled(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        convertToTripitakaSin();
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnicodePopup().setVisible(true);
            }
        });
    }

    public void setOutputTextField(JTextField fld){
        this.jtf=fld;
    }

    public void setSearchButton(JButton jbt){
        this.srchBtn=jbt;
    }

    public void setLaunchBtn(JButton jlb){
        this.launchBtn=jlb;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

        private void convertToTripitakaSin() {
        String text = jTextField1.getText();
        text = text.replace(".", "�");
        text = text.replace(",", "￦");
        text = text.replace("\\", "�");
        text = text.replace("ත්‍රෛ", "ff;1");
        text = text.replace("ශෛ", "ffY");
        text = text.replace("චෛ", "ffp");
        text = text.replace("ජෛ", "ffp");
        text = text.replace("කෛ", "ffl");
        text = text.replace("මෛ", "ffu");
        text = text.replace("පෛ", "ffm");
        text = text.replace("දෛ", "ffo");
        text = text.replace("තෛ", "ff;");
        text = text.replace("නෛ", "ffk");
        text = text.replace("ධෛ", "ffO");
        text = text.replace("වෛ", "ffj");
        text = text.replace("ප්‍රෞ", "fm1#");
        text = text.replace("ෂ්‍යෝ", "fIHda");
        text = text.replace("ඡ්‍යෝ", "fPHda");
        text = text.replace("ඪ්‍යෝ", "fVHda");
        text = text.replace("ඝ්‍යෝ", "f>Hda");
        text = text.replace("ඛ්‍යෝ", "f>Hda");
        text = text.replace("ළ්‍යෝ", "f<Hdaaaa");
        text = text.replace("ඵ්‍යෝ", "fMHdaaaa");
        text = text.replace("ඨ්‍යෝ", "fGHdaaaa");
        text = text.replace("ශ්‍යෝ", "fYHda");
        text = text.replace("ක්‍ෂ්‍යෝ", "fCIHda");
        text = text.replace("බ්‍යෝ", "fLHda");
        text = text.replace("ච්‍යෝ", "fpHdaaaa");
        text = text.replace("ඩ්‍යෝ", "fvHdaaaa");
        text = text.replace("ෆ්‍යෝ", "f\\Hdaaaa");
        text = text.replace("ග්‍යෝ", "f.Hda");
        text = text.replace("ජ්‍යෝ", "fcHdaa");
        text = text.replace("ක්‍යෝ", "flHdaa");
        text = text.replace("ල්‍යෝ", "f,Hdaaa");
        text = text.replace("ම්‍යෝ", "fuHdaaaa");
        text = text.replace("න්‍යෝ", "fkHdaa");
        text = text.replace("ප්‍යෝ", "fmHdaaaa");
        text = text.replace("ද්‍යෝ", "foHda");
        text = text.replace("ස්‍යෝ", "fiHda");
        text = text.replace("ට්‍යෝ", "fgHda");
        text = text.replace("ව්‍යෝ", "fjHda");
        text = text.replace("ත්‍යෝ", "f;Hda");
        text = text.replace("භ්‍යෝ", "fNHda");
        text = text.replace("ධ්‍යෝ", "fOHda");
        text = text.replace("ථ්‍යෝ", "f:Hda");
        text = text.replace("ෂ්‍යො", "fIHd");
        text = text.replace("ශ්‍යො", "fYHd");
        text = text.replace("ඛ්‍යො", "fLHd");
        text = text.replace("ක්‍ෂ්‍යො", "fCIHd");
        text = text.replace("බ්‍යො", "fnHd");
        text = text.replace("ව්‍යො", "fjHd");
        text = text.replace("ඩ්‍යො", "fvHd");
        text = text.replace("ෆ්‍යො", "f\\Hd");
        text = text.replace("ග්‍යො", "f.Hd");
        text = text.replace("ජ්‍යො", "fcHd");
        text = text.replace("ක්‍යො", "flHd");
        text = text.replace("ම්‍යො", "fuHd");
        text = text.replace("ප්‍යො", "fmHd");
        text = text.replace("ද්‍යො", "foHd");
        text = text.replace("ස්‍යො", "fiHd");
        text = text.replace("ට්‍යො", "fgHd");
        text = text.replace("ව්‍යො", "fjHd");
        text = text.replace("ත්‍යො", "f;Hd");
        text = text.replace("භ්‍යො", "fNHd");
        text = text.replace("ධ්‍යො", "fOHd");
        text = text.replace("ථ්‍යො", "f:Hd");
        text = text.replace("ෂ්‍යෙ", "fIH");
        text = text.replace("ඡ්‍යෙ", "fPH");
        text = text.replace("ළ්‍යෙ", "f<HH");
        text = text.replace("ණ්‍යෙ", "fKH");
        text = text.replace("ච්‍යෙ", "fpH");
        text = text.replace("ල්‍යෙ", "f,H");
        text = text.replace("න්‍යෙ", "fkH");
        text = text.replace("ශ්‍යෙ", "fYH");
        text = text.replace("ඛ්‍යෙ", "fLH");
        text = text.replace("ක්‍ෂ්යෙ", "fCIah");
        text = text.replace("බ්‍යෙ", "fLH");
        text = text.replace("ඩ්‍යෙ", "fvH");
        text = text.replace("ෆ්‍යෙ", "f\\H");
        text = text.replace("ග්‍යෙ", "f.H");
        text = text.replace("ජ්‍යෙ", "fcH");
        text = text.replace("ක්‍යෙ", "flH");
        text = text.replace("ම්‍යෙ", "fuH");
        text = text.replace("ප්‍යෙ", "fmH");
        text = text.replace("ද්‍යෙ", "foH");
        text = text.replace("ස්‍යෙ", "fLH");
        text = text.replace("ට්‍යෙ", "fgH");
        text = text.replace("ව්‍යෙ", "fjH");
        text = text.replace("ත්‍යෙ", "f;H");
        text = text.replace("භ්‍යෙ", "fNH");
        text = text.replace("ධ්‍යෙ", "fOH");
        text = text.replace("ථ්‍යෙ", "f:H");
        text = text.replace("ෂ්‍රෝ", "fI1da");
        text = text.replace("ඝ්‍රෝ", "f>1da");
        text = text.replace("ශ්‍රෝ", "fY1da");
        text = text.replace("ක්‍ෂ්‍රෝ", "fCI1da");
        text = text.replace("බ්‍රෝ", "fL1da");
        text = text.replace("ඩ්‍රෝ", "fv1da");
        text = text.replace("ෆ්‍රෝ", "f\\1da");
        text = text.replace("ග්‍රෝ", "f.1da");
        text = text.replace("ක්‍රෝ", "fl1da");
        text = text.replace("ප්‍රෝ", "fm1da");
        text = text.replace("ද්‍රෝ", "fÊda");
        text = text.replace("ස්‍රෝ", "fi1da");
        text = text.replace("ට්‍රෝ", "fg1da");
        text = text.replace("ත්‍රෝ", "f;1da");
        text = text.replace("ශ්‍රො", "fY1d");
        text = text.replace("ඩ්‍රො", "fv1d");
        text = text.replace("ෆ්‍රො", "f\\1d");
        text = text.replace("ග්‍රො", "f.1d");
        text = text.replace("ක්‍රො", "fl1d");
        text = text.replace("ප්‍රො", "fm1d");
        text = text.replace("ද්‍රො", "fÊd");
        text = text.replace("ස්‍රො", "fi1d");
        text = text.replace("ට්‍රො", "fg1d");
        text = text.replace("ත්‍රො", "f;1d");
        text = text.replace("ශ්‍රේ", "fY1a");
        text = text.replace("බ්‍රේ", "fn1z");
        text = text.replace("ඩ්‍රේ", "fvz1");
        text = text.replace("ෆ්‍රේ", "f\\1a");
        text = text.replace("ග්‍රේ", "f.1a");
        text = text.replace("ක්‍රේ", "fl1a");
        text = text.replace("ප්‍රේ", "fm1a");
        text = text.replace("ද්‍රේ", "fÊa");
        text = text.replace("ස්‍රේ", "fi1a");
        text = text.replace("ත්‍රේ", "f;1a");
        text = text.replace("ධ්‍රේ", "fO1z");
        text = text.replace("ෂ්‍රෙ", "fI1a");
        text = text.replace("ශ්‍රෙ", "fY1a");
        text = text.replace("බ්‍රෙ", "fL1");
        text = text.replace("ෆ්‍රෙ", "f\\1");
        text = text.replace("ග්‍රෙ", "f.1");
        text = text.replace("ක්‍රෙ", "fl1");
        text = text.replace("ප්‍රෙ", "fm1");
        text = text.replace("ද්‍රෙ", "fÊ");
        text = text.replace("ස්‍රෙ", "fi1");
        text = text.replace("ත්‍රෙ", "f;1");
        text = text.replace("භ්‍රෙ", "fN1");
        text = text.replace("ධ්‍රෙ", "fO1");
        text = text.replace("්‍ය", "H");
        text = text.replace("්‍ර", "1");
        text = text.replace("ෂෞ", "fI#");
        text = text.replace("ඡෞ", "fP#");
        text = text.replace("ශෞ", "fY#");
        text = text.replace("බෞ", "fn#");
        text = text.replace("චෞ", "fp#");
        text = text.replace("ඩෞ", "fv#");
        text = text.replace("ෆෞ", "f\\#");
        text = text.replace("ගෞ", "f.#");
        text = text.replace("ජෞ", "fc#");
        text = text.replace("කෞ", "fl#");
        text = text.replace("ලෞ", "f,#");
        text = text.replace("මෞ", "fu#");
        text = text.replace("නෞ", "fk#");
        text = text.replace("පෞ", "fm#");
        text = text.replace("දෞ", "fo#");
        text = text.replace("රෞ", "fr#");
        text = text.replace("සෞ", "fi#");
        text = text.replace("ටෞ", "fg#");
        text = text.replace("තෞ", "f;#");
        text = text.replace("භෞ", "fN#");
        text = text.replace("ඤෞ", "f[#");
        text = text.replace("ෂෝ", "fIda");
        text = text.replace("ඹෝ", "fUda");
        text = text.replace("ඡෝ", "fPda");
        text = text.replace("ඪෝ", "fVda");
        text = text.replace("ඝෝ", "f>da");
        text = text.replace("ඛෝ", "fLda");
        text = text.replace("ළෝ", "f<da");
        text = text.replace("ඟෝ", "fZ.dA");
        text = text.replace("ණෝ", "fKda");
        text = text.replace("ඵෝ", "fMda");
        text = text.replace("ඨෝ", "fGda");
        text = text.replace("ඬෝ", "fda");
        text = text.replace("ශෝ", "fYda");
        text = text.replace("ඥෝ", "f{da");
        text = text.replace("ඳෝ", "fZoda");
        text = text.replace("ක්‍ෂෝ", "fCIda");
        text = text.replace("බෝ", "fnda");
        text = text.replace("චෝ", "fpda");
        text = text.replace("ඩෝ", "fvda");
        text = text.replace("ෆෝ", "f\\da");
        text = text.replace("ගෝ", "f.da");
        text = text.replace("හෝ", "fyda");
        text = text.replace("ජෝ", "fcda");
        text = text.replace("කෝ", "flda ");
        text = text.replace("ලෝ", "f,da");
        text = text.replace("මෝ", "fuda");
        text = text.replace("නෝ", "fkda ");
        text = text.replace("පෝ", "fmda");
        text = text.replace("දෝ", "foda");
        text = text.replace("රෝ", "frda");
        text = text.replace("සෝ", "fida");
        text = text.replace("ටෝ", "fgda");
        text = text.replace("වෝ", "fjda");
        text = text.replace("තෝ", "f;da");
        text = text.replace("භෝ", "fNda");
        text = text.replace("යෝ", "fhda");
        text = text.replace("ඤෝ", "f[da");
        text = text.replace("ධෝ", "fOda");
        text = text.replace("ථෝ", "f:da");
        text = text.replace("ෂො", "fId");
        text = text.replace("ඹො", "fUd");
        text = text.replace("ඡො", "fPd");
        text = text.replace("ඪො", "fVd");
        text = text.replace("ඝො", "f>d");
        text = text.replace("ඛො", "fLd");
        text = text.replace("ළො", "f<d");
        text = text.replace("ඟො", "fÕd");
        text = text.replace("ණො", "fKd");
        text = text.replace("ඵො", "fMd");
        text = text.replace("ඨො", "fGd");
        text = text.replace("ඬො", "fËd");
        text = text.replace("ශො", "fYd");
        text = text.replace("ඥො", "f{d");
        text = text.replace("ඳො", " f d");
        text = text.replace("ක්‍ෂො", "fCId");
        text = text.replace("බො", " fnd ");
        text = text.replace("චො", "fpd");
        text = text.replace("ඩො", "fvd");
        text = text.replace("ෆො", "f\\d");
        text = text.replace("ගො", "f.d");
        text = text.replace("හො", "fyd");
        text = text.replace("ජො", "fcd");
        text = text.replace("කො", "fld");
        text = text.replace("ලො", "f,d");
        text = text.replace("මො", "fud");
        text = text.replace("නො", "fkd");
        text = text.replace("පො", "fmd");
        text = text.replace("දො", "fod");
        text = text.replace("රො", "frd");
        text = text.replace("සො", "fid ");
        text = text.replace("ටො", "fgd");
        text = text.replace("වො", "fjd");
        text = text.replace("තො", "f;d");
        text = text.replace("භො", "fNd");
        text = text.replace("යො", "fhd");
        text = text.replace("ඤො", "f[d");
        text = text.replace("ධො", "fOd");
        text = text.replace("ථො", "f:d");
        text = text.replace("ෂේ", "fIa");
        text = text.replace("ඹේ", "fUz");
        text = text.replace("ඡේ", "fPa");
        text = text.replace("ඪේ", "fVa");
        text = text.replace("ඝේ", "f>a");
        text = text.replace("ඛේ", "fLz");
        text = text.replace("ළේ", "f<a");
        text = text.replace("ඟේ", "fZ.a");
        text = text.replace("ණේ", "fKa");
        text = text.replace("ඵේ", "fMa");
        text = text.replace("ඨේ", "fGa");
        text = text.replace("ඬේ", "fZvz");
        text = text.replace("ශේ", "fYa");
        text = text.replace("ඥේ", "f{a");
        text = text.replace("ඳේ", "fZoa");
        text = text.replace("ක්‍ෂේ", "fCIa");
        text = text.replace("බේ", "fnz");
        text = text.replace("චේ", "fpz");
        text = text.replace("ඩේ", "fvz");
        text = text.replace("ෆේ", "f\\a");
        text = text.replace("ගේ", "f.a");
        text = text.replace("හේ", "fya");
        text = text.replace("පේ", "fma");
        text = text.replace("කේ", "fla");
        text = text.replace("ලේ", "f,a");
        text = text.replace("මේ", "fuz");
        text = text.replace("නේ", "fka");
        text = text.replace("ජේ", "fca");
        text = text.replace("දේ", "foa");
        text = text.replace("රේ", "frA");
        text = text.replace("සේ", "fia");
        text = text.replace("ටේ", "fgz");
        text = text.replace("වේ", "fjz");
        text = text.replace("තේ", "f;a");
        text = text.replace("භේ", "fNa");
        text = text.replace("යේ", "fha");
        text = text.replace("ඤේ", "f[a");
        text = text.replace("ධේ", "fOz");
        text = text.replace("ථේ", "f:a");
        text = text.replace("ෂෙ", "fI");
        text = text.replace("ඹෙ", "fU");
        text = text.replace("ඓ", "ft");
        text = text.replace("ඡෙ", "fP");
        text = text.replace("ඪෙ", "fV");
        text = text.replace("ඝෙ", "f>");
        text = text.replace("ඛෙ", "fL");
        text = text.replace("ළෙ", "f<");
        text = text.replace("ඟෙ", "fZ.");
        text = text.replace("ණෙ", "fK");
        text = text.replace("ඵෙ", "fM");
        text = text.replace("ඨෙ", "fG");
        text = text.replace("ඬෙ", "fZv");
        text = text.replace("ශෙ", "fY");
        text = text.replace("ඥෙ", "f{");
        text = text.replace("ඳෙ", "fZo");
        text = text.replace("ක්‍ෂෙ", "fCI");
        text = text.replace("බෙ", "fn");
        text = text.replace("චෙ", "fp");
        text = text.replace("ඩෙ", "fv");
        text = text.replace("ෆෙ", "f\\");
        text = text.replace("ගෙ", "f.");
        text = text.replace("හෙ", "fy");
        text = text.replace("ජෙ", "fc");
        text = text.replace("කෙ", "fl");
        text = text.replace("ලෙ", "f,");
        text = text.replace("මෙ", "fu");
        text = text.replace("නෙ", "fk");
        text = text.replace("පෙ", "fm");
        text = text.replace("දෙ", "fo");
        text = text.replace("රෙ", "fr");
        text = text.replace("සෙ", "fi");
        text = text.replace("ටෙ", "fg");
        text = text.replace("වෙ", "fj");
        text = text.replace("තෙ", "f;");
        text = text.replace("භෙ", "fN");
        text = text.replace("යෙ", "fh");
        text = text.replace("ඤෙ", "f[");
        text = text.replace("ධෙ", "fO");
        text = text.replace("ථෙ", "f:");
        text = text.replace("තු", ";2");
        text = text.replace("ගු", ".2");
        text = text.replace("කු", "fl2");
        text = text.replace("තූ", ";@");
        text = text.replace("ගූ", ".@");
        text = text.replace("කූ", "l@");
        text = text.replace("රු", "re");
        text = text.replace("රූ", "rE");
        text = text.replace("ආ", "wd");
        text = text.replace("ඇ", "we");
        text = text.replace("ඈ", "wE");
        text = text.replace("ඌ", "W#");
        text = text.replace("ඖ", "T#");
        text = text.replace("ඒ", "ta");
        text = text.replace("ඕ", "Tz");
        text = text.replace("ඳි", "Ës");
        text = text.replace("ඳී", "ËS");
        text = text.replace("දූ", "É");
        text = text.replace("දී", "oS");
        text = text.replace("ලූ", ",Q");
        text = text.replace("ර්‍ය", "h!");
        text = text.replace("ඳූ", "Ì");
        text = text.replace("ර්", "rA");
        text = text.replace("ඨි", "Gs");
        text = text.replace("ඨී", "GS");
        text = text.replace("ඡී", "PS");
        text = text.replace("ඛ්", "Lz");
        text = text.replace("ඛි", "Ls");
        text = text.replace("ලු", ",q");
        text = text.replace("ඛී", "LS");
        text = text.replace("දි", "os");
        text = text.replace("ච්", "pz");
        text = text.replace("ජ්", "ca");
        text = text.replace("රී", "rS");
        text = text.replace("ඪී", "VS");
        text = text.replace("ඪී", "VS");
        text = text.replace("චි", "ps");
        text = text.replace("ථී", ":S");
        text = text.replace("ථී", ":S");
        text = text.replace("ජී", "cS");
        text = text.replace("චී", "pS");
        text = text.replace("ඞ්", "Xz");
        text = text.replace("ඵී", "MS");
        text = text.replace("ට්", "gz");
        text = text.replace("ඵි", "Ms");
        text = text.replace("රි", "rs");
        text = text.replace("ටී", "gS");
        text = text.replace("ටි", "gs");
        text = text.replace("ඩ්", "vz");
        text = text.replace("ඩී", "vS");
        text = text.replace("ඩි", "vs");
        text = text.replace("ඬ්", "Zvz");
        text = text.replace("ඬි", "ç");
        text = text.replace("ධ්", "Oz");
        text = text.replace("ඬී", "é");
        text = text.replace("ධි", "Os");
        text = text.replace("ධී", "OS");
        text = text.replace("බි", "ns");
        text = text.replace("බ්", "nz");
        text = text.replace("බී", "nS");
        text = text.replace("ම්", "uz");
        text = text.replace("ජි", "cs");
        text = text.replace("මි", "us");
        text = text.replace("ඹ්", "Uz");
        text = text.replace("මී", "uS");
        text = text.replace("ඹි", "US");
        text = text.replace("ව්", "jz");
        text = text.replace("ඹී", "Us");
        text = text.replace("ඳු", "Ì");
        text = text.replace("ද්‍ර", "Ê");
        text = text.replace("වී", "jS");
        text = text.replace("වි", "js");
        text = text.replace("ඞ්", "Xz");
        text = text.replace("ඞී", "X");
        text = text.replace("ඡි", "Ps");
        text = text.replace("ඡ්", "Pa");
        text = text.replace("දු", "È");
        text = text.replace("ජ්", "cA");
        text = text.replace("ර්‍ණ", "K!");
        text = text.replace("ණී", "KS");
        text = text.replace("ජී", "cS");
        text = text.replace("ඡි", "Ps");
        text = text.replace("ඩි", "vs");
        text = text.replace("ඤු", "ZCÌ");
        text = text.replace("ග", ".");
        text = text.replace("ළු", "ZM");
        text = text.replace("ෂ", "I");
        text = text.replace("ං", "x");
        text = text.replace("ඃ", "%");
        text = text.replace("ඹ", "U");
        text = text.replace("ඡ", "P");
        text = text.replace("ඪ", "V");
        text = text.replace("ඝ", ">");
        text = text.replace("ඊ", "B");
        text = text.replace("ඣ", "CO");
        text = text.replace("ඛ", "L");
        text = text.replace("ළ", "<");
        text = text.replace("ඟ", "Z.");
        text = text.replace("ණ", "K");
        text = text.replace("ඵ", "M");
        text = text.replace("ඨ", "G");
        text = text.replace("ඃ", "%");
        text = text.replace("\"", "Ù");
        text = text.replace("/", "^");
        text = text.replace(")", "(");
        //text = text.replace(":", "_");
        text = text.replace("-", "+");
        text = text.replace("ෆ", "\\");
        text = text.replace("ල", ",");
        text = text.replace("-", "+");
        text = text.replace("රැ", "/");
        text = text.replace("ථ", ":");
        text = text.replace("ත", ";");
        text = text.replace("ළ", "<");
        text = text.replace("ඝ", ">");
        text = text.replace("රෑ", "?");
        text = text.replace("ඊ", "B");
        text = text.replace("ක‍", "l");
        text = text.replace("ෘ", "D");
        text = text.replace("ෑ", "E");
        text = text.replace("ත‍", ";");
        text = text.replace("ඨ", "G");
        text = text.replace("්‍ය", "H");
        text = text.replace("ෂ", "I");
        text = text.replace("න‍", "k");
        text = text.replace("ණ", "K");
        text = text.replace("ඛ", "L");
        text = text.replace("ඵ", "M");
        text = text.replace("භ", "N");
        text = text.replace("ධ", "O");
        text = text.replace("ඡ", "P");
        text = text.replace("ඍ", "RD");
        text = text.replace("ඔ", "T");
        text = text.replace("ඹ", "U");
        text = text.replace("ඪ", "V");
        text = text.replace("උ", "W");
        text = text.replace("ශ", "Y");
        text = text.replace("ඤ", "[");
        text = text.replace("ඉ", "b");
        text = text.replace("ජ", "c");
        text = text.replace("ට", "g");
        text = text.replace("ය", "h");
        text = text.replace("ස", "i");
        text = text.replace("ව", "j");
        text = text.replace("න", "k");
        text = text.replace("ක", "l");
        text = text.replace("ප", "m");
        text = text.replace("බ", "n");
        text = text.replace("ද", "o");
        text = text.replace("ච", "p");
        text = text.replace("ර", "r");
        text = text.replace("එ", "t");
        text = text.replace("ම", "u");
        text = text.replace("ඩ", "v");
        text = text.replace("අ", "w");
        text = text.replace("හ", "y");
        text = text.replace("ඥ", "{");
        text = text.replace("ඳ", "Ë");
        text = text.replace("ක්‍ෂ", "CI");
        text = text.replace("ැ", "e");
        text = text.replace("ෑ", "E");
        text = text.replace("ෙ", "f");
        text = text.replace("ු", "q");
        text = text.replace("ි", "s");
        text = text.replace("ූ", "Q");
        text = text.replace("ී", "S");
        text = text.replace("ෘ", "D");
        text = text.replace("ෲ", "DD");
        text = text.replace("ෟ", "#");
        text = text.replace("ා", "d");
        text = text.replace("්", "a");
        text = text.replace("￦", "\"");
        text = text.replace("�", "\'");
        text = text.replace("￫", "*");
        text = text.replace("￩", "(");
        text = text.replace("ￕ", "]");
        text = text.replace("$", "^");
        text = text.replace("ￔ", "+");
        text = text.replace("ￓ", "$");
        text = text.replace("ￒ", "Ø");
        text = text.replace("ￏ", "±");
        text = text.replace("ￎ", ")");
        text = text.replace("ￍ", "±");
        text = text.replace("ￌ", "_");
        text = text.replace("ￋ", "^");
        text = text.replace("ﾶ", "Õ");
        //text = text.replace("0", "=");
        //text = text.replace("9", "-");
        //text = text.replace("8", "0");
        //text = text.replace("7", "9");
        //text = text.replace("6", "8");
        //text = text.replace("5", "7");
        //text = text.replace("4", "6");
        //text = text.replace("3", "5");
        //text = text.replace("2", "4");
        //text = text.replace("1", "3");
        this.jtf.setText(text);
    }
}
